//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMVC1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_materia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_materia()
        {
            this.tbl_detalle_profesor_materia = new HashSet<tbl_detalle_profesor_materia>();
        }
    
        public int idMateria { get; set; }
        public string nombreMateria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_detalle_profesor_materia> tbl_detalle_profesor_materia { get; set; }
    }
}
