//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMVC1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_detalle_profesor_materia
    {
        public int id { get; set; }
        public Nullable<int> idProfesor { get; set; }
        public Nullable<int> idMateria { get; set; }
    
        public virtual tbl_materia tbl_materia { get; set; }
        public virtual tbl_profesor tbl_profesor { get; set; }
    }
}
